Changes to run with 0.1-alpha
lolopinto/ent-starter pull request #5
Opened 2022-11-10 14:14 UTC by mrtom

Using the `ent-starter` template today fails when running `npm run codegen` with a TS error.

Honestly I didn't look into it much (and can do if useful), but instead upgraded everything to the 0.1-alpha version. After this problem the issue goes away.

Given the [docs](https://ent.dev/docs/intro) are using the 0.1 format already I figure this project should just be updated to match.

I also added a `.nvmrc` file for Node 17

2022-11-10 19:04 UTC, lolopinto commented
thanks for doing this. has been on my list but i somehow hadn't done it for some reason

i even have https://github.com/lolopinto/ent-starter/tree/v0.1 which has some of this but not all of it

2022-11-10 19:07 UTC, lolopinto requested changes
some changes

2022-11-10 19:07 UTC, lolopinto commented on Dockerfile
> +FROM ghcr.io/lolopinto/ent:0.1.0-alpha.5-nodejs-17-dev
can you update to `ghcr.io/lolopinto/ent:0.1.0-alpha.30-nodejs-17-slim`

that's the latest

2022-11-10 19:07 UTC, lolopinto commented on README.md
>  // src/schema/user.ts
`user_schema.ts`

2022-11-10 19:07 UTC, lolopinto commented on README.md
>  // src/schema/user.ts
`user_schema.ts`

2022-11-10 19:07 UTC, lolopinto commented on README.md
>  // src/schema/user.ts
`user_schema.ts`

2022-11-10 19:07 UTC, lolopinto commented on README.md
> +// src/schema/user.ts
`user_schema.ts`

2022-11-10 19:07 UTC, lolopinto commented on package.json
> +    "@snowtop/ent": "^0.1.0-alpha34",
`^0.1.0-alpha93`

2022-11-10 19:07 UTC, lolopinto commented on develop.Dockerfile
> +FROM ghcr.io/lolopinto/ent:0.1.0-alpha.5-nodejs-17-dev
`ghcr.io/lolopinto/ent:0.1.0-alpha.30-nodejs-17-dev`

2022-11-11 11:38 UTC, mrtom commented
OK, hopefully all fixed. I created a new repo from my copy of the template and checked I could run through the README with pg and spin up the GQL server without issue too.

2022-11-11 18:50 UTC, lolopinto approved these changes

2022-11-11 18:50 UTC, merged

2022-11-11 18:51 UTC, lolopinto commented
thanks!